export const FETCH_ENTRIES = 'FETCH_ENTRIES';
export const FILTER_ENTRIES_NAME = 'FILTER_ENTRIES_NAME';
export const FILTER_ENTRIES_DAY = 'FILTER_ENTRIES_DAY';
export const FILTER_ENTRIES_TIME = 'FILTER_ENTRIES_TIME';
export const FILTER_UPDATE_TYPE = 'UPDATE_FILTER_TYPE';
export const FILTER_RESET_NAME = 'FILTER_RESET_NAME';
export const FILTER_RESET_DAYTIME = 'FILTER_RESET_DAYTIME';
export const FILTER_COUNT = 'FILTER_COUNT';

export const FETCH_USERS = 'FETCH_USERS';
export const LOGIN_USER = 'LOGIN_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USER = 'GET_USER';
export const GET_SHARE_LIST = 'GET_SHARE_LIST';
export const ADD_SHARE_LIST = 'ADD_SHARE_LIST';

export const CREATE_LIST = 'CREATE_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const RENAME_LIST = 'RENAME_LIST';
export const REMOVE_FROM_LIST = 'UPDATE_LIST';